# TODO: Add GPG signing key once a key pair is generated.
#   rpm --addsign ~/rpmbuild/RPMS/x86_64/backup-tool-*.rpm
#   Distribute the public key alongside the .rpm for user verification.
Name:           backup-tool
Version:        0.1.7
Release:        1%{?dist}
Summary:        GTK4 home-directory backup manager using rsync and systemd

License:        GPL-3.0-or-later
URL:            https://github.com/NormG/Backup-Tool

# Source0: project source tarball
# Source1: vendored Rust dependencies (generated by 'cargo vendor')
Source0:        %{name}-%{version}.tar.gz
Source1:        %{name}-%{version}-vendor.tar.gz

# ── Build dependencies ────────────────────────────────────────────────────────
BuildRequires:  rust >= 1.70
BuildRequires:  cargo
BuildRequires:  pkgconf-pkg-config
BuildRequires:  gtk4-devel
BuildRequires:  glib2-devel
BuildRequires:  gcc

# ── Runtime dependencies ──────────────────────────────────────────────────────
Requires:       rsync
Requires:       gtk4
Requires:       hicolor-icon-theme
# udisks2 enables auto-mounting the backup drive by UUID (optional but recommended)
Recommends:     udisks2

%description
Home Backup is a GTK4 desktop application for Fedora Linux that backs up a
home directory to an external drive using rsync atomic snapshots and a
systemd user timer.

Features:
  - Guided 7-page install wizard with live drive detection
  - Seven-tab management window (Dashboard, Schedule, Excludes,
    Paths, Log, BTRFS, About)
  - Atomic rsync snapshots staged in .inprogress-* and renamed on success
  - Hardlinked incrementals via --link-dest; only deltas consume new space
  - Configurable full/incremental schedule, retention, and exclude patterns
  - Systemd user-level timer — no root required
  - Nautilus sidebar bookmark management
  - Same-filesystem destination guard

# ── Prep ─────────────────────────────────────────────────────────────────────
# -a 1  unpacks Source1 (vendor tarball) after changing into the build dir
%prep
%autosetup -n %{name}-%{version} -a 1

# Configure cargo to use the local vendor directory instead of crates.io.
mkdir -p .cargo
cat > .cargo/config.toml << 'CARGO_EOF'
[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
CARGO_EOF

# ── Build ─────────────────────────────────────────────────────────────────────
%build
cargo build --release --offline

# ── Install ───────────────────────────────────────────────────────────────────
%install
# Binary
install -Dm 0755 target/release/%{name} \
    %{buildroot}%{_bindir}/%{name}

# Icons
install -Dm 0644 assets/%{name}.png \
    %{buildroot}%{_datadir}/icons/hicolor/128x128/apps/%{name}.png
install -Dm 0644 assets/%{name}.svg \
    %{buildroot}%{_datadir}/icons/hicolor/scalable/apps/%{name}.svg

# Desktop launcher — substitute @EXEC@ with the installed binary path
install -dm 0755 %{buildroot}%{_datadir}/applications
sed 's|@EXEC@|%{_bindir}/%{name}|g' assets/%{name}.desktop \
    > %{buildroot}%{_datadir}/applications/%{name}.desktop

# Assets directory (runtime icon lookup: systemd.rs searches next to the binary)
install -dm 0755 %{buildroot}%{_datadir}/%{name}
cp -r assets %{buildroot}%{_datadir}/%{name}/assets

# License and documentation
install -Dm 0644 LICENSE \
    %{buildroot}%{_licensedir}/%{name}/LICENSE
install -Dm 0644 README.md \
    %{buildroot}%{_pkgdocdir}/README.md

# ── Post-install scriptlets ───────────────────────────────────────────────────
%post
gtk-update-icon-cache -f -t %{_datadir}/icons/hicolor &>/dev/null || :
update-desktop-database -q %{_datadir}/applications          &>/dev/null || :
# Create Btrfs snapshot directory, world-writable with sticky bit (like /tmp)
# so any user can create their own snapshots without needing root.
mkdir -p /home/.snapshots 2>/dev/null || :
chmod 1777 /home/.snapshots 2>/dev/null || :

# Drop legacy home-backup user systemd units after the 0.1.7 rename.
migrate_home_backup_user_units() {
    local user="$1"
    local home
    home=$(getent passwd "$user" | cut -d: -f6) || return 0
    [ -n "$home" ] || return 0
    [ -d "$home" ] || return 0

    local ud="$home/.config/systemd/user"
    if [ -f "$ud/home-backup.timer" ] || [ -f "$ud/home-backup.service" ]; then
        runuser -u "$user" -- systemctl --user disable --now home-backup.timer \
            &>/dev/null || true
        rm -f "$ud/home-backup.service" "$ud/home-backup.timer"
        runuser -u "$user" -- systemctl --user daemon-reload &>/dev/null || true
    fi

    rm -f "$home/.local/share/applications/home-backup.desktop"
}

if [ -n "${SUDO_USER:-}" ]; then
    migrate_home_backup_user_units "$SUDO_USER"
fi

%postun
gtk-update-icon-cache -f -t %{_datadir}/icons/hicolor &>/dev/null || :
update-desktop-database -q %{_datadir}/applications          &>/dev/null || :

# ── File manifest ─────────────────────────────────────────────────────────────
%files
%license LICENSE
%doc README.md
%{_bindir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/128x128/apps/%{name}.png
%{_datadir}/icons/hicolor/scalable/apps/%{name}.svg
%{_datadir}/%{name}/

# ── Changelog ─────────────────────────────────────────────────────────────────
%changelog
* Sun Aug  2 2026 norm <norm@localhost> - 0.1.7-1
- Rename package and binary from home-backup to backup-tool
- Add missing 128x128 PNG app icon; align docs, install.sh, and spec
- RPM post-install: remove legacy home-backup user timer/service units

* Sun Jul 27 2026 norm <norm@localhost> - 0.1.6-1
- BTRFS tab: Refresh and Delete buttons for sent archives list

* Sun Jul 27 2026 norm <norm@localhost> - 0.1.5-1
- BTRFS send/receive Phase 2; pkexec fallback for permission errors

* Sun Jul 27 2026 norm <norm@localhost> - 0.1.4-1
- RPM packaging introduced; package-rpm.sh build script added
- Fix: Paths tab now shows live-detected drive label
- Docs: finalized README with RPM install, systemd commands, uninstall

* Sun Jul 27 2026 norm <norm@localhost> - 0.1.3-1
- Initial RPM package
- GTK4 home-directory backup manager with wizard and management window
- Atomic rsync snapshots with hardlinked incrementals
- Systemd user timer, Nautilus bookmark integration
